version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-${ENV}
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_${ENV}:/var/lib/postgresql/data

  order-service:
    image: order-service:${IMAGE_TAG}
    container_name: order-${ENV}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env.${ENV}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${SPRING_DATASOURCE_DB}
      LOGGING_FILE_PATH: ${LOGGING_FILE_PATH}
    volumes:
      - ./logs:${LOGGING_FILE_PATH}
    depends_on:
      - postgres

volumes:
  postgres_data_dev:
  postgres_data_stage:
