name: CI-CD Order Service

on:
  push:
    branches:
      - dev
      - stage
  pull_request:

jobs:

  build-test-sonar:
    name: Test, Build & Sonar
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & Test
        working-directory: order-microservice
        run: mvn clean verify

      - name: Sonar Scan
        working-directory: order-microservice
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.organization=taher2011 \
            -Dsonar.projectKey=Taher2011_ecommerce-microservices \
            -Dsonar.projectName=order-service \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.branch.name=${{ github.ref_name }}

      - name: Package JAR
        working-directory: order-microservice
        run: mvn package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: order-service-jar
          path: order-microservice/target/*.jar


  docker-build-push-deploy:
    name: Docker Build → Push → Deploy EC2
    runs-on: ubuntu-latest
    needs: build-test-sonar

    if: github.event_name == 'push'
    environment: ${{ github.ref_name }}

    env:
      IMAGE_NAME: taher2011/order-service
      IMAGE_TAG: ${{ github.ref_name }}
      IMAGE_SHA_TAG: ${{ github.sha }}

      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: order-service-jar
          path: order-microservice/target

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Safe Docker Tag
        run: |
          echo "SAFE_TAG=${IMAGE_TAG//\//-}" >> $GITHUB_ENV

      - name: Build Docker Image
        working-directory: order-microservice
        run: |
          docker build \
            -t $IMAGE_NAME:$SAFE_TAG \
            -t $IMAGE_NAME:$IMAGE_SHA_TAG .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$SAFE_TAG
          docker push $IMAGE_NAME:$IMAGE_SHA_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_NAME,SAFE_TAG,IMAGE_TAG,DB_URL,DB_USERNAME,DB_PASSWORD,LOGGING_FILE_PATH

          script: |
            echo "Deploying environment: $IMAGE_TAG"

            if [ "$IMAGE_TAG" = "dev" ]; then
              CONTAINER_NAME=order-service-dev
            elif [ "$IMAGE_TAG" = "stage" ]; then
              CONTAINER_NAME=order-service-stage
            else
              echo "Unknown environment"
              exit 1
            fi

            docker pull $IMAGE_NAME:$SAFE_TAG

            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            docker run -d \
              --name $CONTAINER_NAME \
              --network host \
              -e AWS_REGION=us-east-1 \
              -e SPRING_PROFILES_ACTIVE=$IMAGE_TAG \
              -e SPRING_DATASOURCE_URL=$DB_URL \
              -e SPRING_DATASOURCE_USERNAME=$DB_USERNAME \
              -e SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD \              
              -e LOGGING_FILE_PATH=$CONTAINER_LOGGING_FILE_PATH \
              -v $EC2_LOGGING_FILE_PATH:$CONTAINER_LOGGING_FILE_PATH \
              $IMAGE_NAME:$SAFE_TAG

            echo "Deployment completed for $IMAGE_TAG"