name: CI - Build, Test, Sonar & Docker

on:
  push:
    branches:
      - dev
      - stage
  pull_request:

jobs:

  build-test-sonar:
    name: Build, Test & Sonar
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & Test
        working-directory: order-microservice
        run: mvn clean verify

      - name: Sonar Scan
        working-directory: order-microservice
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.organization=taher2011 \
            -Dsonar.projectKey=Taher2011_ecommerce-microservices \
            -Dsonar.projectName=order-service \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.branch.name=${{ github.ref_name }}

      - name: Package JAR
        working-directory: order-microservice
        run: mvn package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: order-service-jar
          path: order-microservice/target/*.jar


  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: build-test-sonar

    env:
      IMAGE_NAME: taher2011/order-service
      IMAGE_TAG: 1.0-${{ github.ref_name }}
      IMAGE_SHA_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: order-service-jar
          path: order-microservice/target

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: order-microservice
        run: |
          docker build \
            -t $IMAGE_NAME:$IMAGE_TAG \
            -t $IMAGE_NAME:$IMAGE_SHA_TAG .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:$IMAGE_SHA_TAG
