name: CI - JUnit, SonarQube & Docker

on:
  push:
    branches:
   #  - dev
      - test
  pull_request:

jobs:

  build-test-sonar:
    name: Build, Test, Sonar & Package JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run Unit Tests & JaCoCo
        working-directory: order-microservice
        run: mvn clean verify

      - name: SonarQube Analysis
        working-directory: order-microservice
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.organization=taher2011 \
            -Dsonar.projectKey=Taher2011_ecommerce-microservices \
            -Dsonar.projectName=order-service \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.branch.name=dev

      - name: Build JAR
        working-directory: order-microservice
        run: mvn package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: order-service-jar
          path: order-microservice/target/*.jar


  docker-build-and-push:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: build-test-sonar

    steps:

      # 1️⃣ Checkout code again
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Download JAR artifact
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: order-service-jar
          path: order-microservice/target

      # 3️⃣ Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build Docker Image
      - name: Build Docker Image
        working-directory: order-microservice
        run: |
          docker build -t order-service:1.0 .

      # 5️⃣ Tag Image for Docker Hub
      - name: Tag Docker Image
        run: |
          docker tag order-service:1.0 taher2011/order-service:1.0

      # 6️⃣ Push Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push taher2011/order-service:1.0
